#!/bin/bash -e
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -z $1 ]; then
	echo "Usage: $0 config.env" >&2
	exit 1
fi

set -a
. "$dir/$1"
set +a

j2 "$dir/template.yaml.j2" > "$dir/template.yaml"

sam package --template-file "$dir/template.yaml" --s3-bucket $deployment_bucket_name --output-template-file "$dir/package.yaml"
aws cloudformation deploy --template-file "$dir/package.yaml" --stack-name $stack_name --capabilities CAPABILITY_IAM
rm "$dir/template.yaml" "$dir/package.yaml"
